FROM mongo:latest
COPY dataset/filmes.json /docker-entrypoint-initdb.d/
COPY dataset/atores.json /docker-entrypoint-initdb.d/
COPY dataset/generos.json /docker-entrypoint-initdb.d/
COPY mongo-init/import.sh /docker-entrypoint-initdb.d/